Reolved errors from yml file
Signed-off-by: Abhi-jith-S <abhijithssa7@gmail.com>

diff --git a/.github/workflows/jiraTicketEnforce.yml b/.github/workflows/jiraTicketEnforce.yml
--- a/.github/workflows/jiraTicketEnforce.yml
+++ b/.github/workflows/jiraTicketEnforce.yml
@@ -18,6 +18,11 @@ jobs:
           git log ${{ github.event.before }}..${{ github.sha }} --pretty=%H > commit_hashes.txt
           error_found=0
           while read commit_hash; do
+          if ! git cat-file -e ${commit_hash}^{commit}; then
+            echo "ERROR: Commit $commit_hash does not exist."
+            error_found=1
+            continue
+          fi
             commit_msg=$(git log -1 --pretty=%B $commit_hash)
             if ! echo "$commit_msg" | grep -Eq '(VPLAY-[0-9]+|RDKEMW-[0-9]+)'; then
               echo "ERROR: Commit $commit_hash does not reference a Jira ticket (VPLAY-xxxx or RDKEMW-xxxx)."
