Enhance L1 tests workflow for Middleware
Added steps for Middleware installation and testing.

diff --git a/.github/workflows/L1-tests.yml b/.github/workflows/L1-tests.yml
--- a/.github/workflows/L1-tests.yml
+++ b/.github/workflows/L1-tests.yml
@@ -13,7 +13,6 @@ jobs:
       # Checkout the aamp repository
       - name: Checkout aamp code
         uses: actions/checkout@v3
-      
       # Install AAMP
       - name: Install AAMP
         run: yes | ./install-aamp.sh -s -k file
@@ -31,23 +30,53 @@ jobs:
         run: |
           python3 parse_gtest_log.py utest_run.log
       
-      # Publish test results
-      - name: Publish L1 test results
+      # Publish AAMP test results
+      - name: Publish AAMP L1 test results
         uses: dorny/test-reporter@v1
         if: always()
         with:
-          name: Unit Test Results
+          name: AAMP Unit Test Results
           path: test/utests/build/ctest-results.xml
           reporter: java-junit
-      
+          
       # Upload artifact (test/utests/build/ctest-results.xml)
-      - name: Upload test result file
+      - name: Upload test result file (test/utests)
         uses: actions/upload-artifact@v4
         with:
-          name: ctest-results
+          name: ctest-results-test-utests-${{ github.run_id }}
           path: test/utests/build/ctest-results.xml
       
       # Show failure
       - name: Show failure details (if any)
         if: failure()
-        run: tail -n 50 test/utests/build/ctest-results.xml
+        run: tail -n 50 test/utests/build/ctest-results.xml || true
+
+      # Install Middleware
+      - name: Install Middleware
+        working-directory: ./middleware
+        run: yes | ./install-middleware.sh -s subtec
+        
+      # Run Middleware L1 tests
+      - name: Run Middleware L1 unit tests
+        working-directory: ./middleware/test/utests
+        run: ./run.sh
+      
+      # Publish Middleware test results
+      - name: Publish Middleware L1 test results
+        uses: dorny/test-reporter@v1
+        with:
+          name: Middleware Unit Test Results
+          path: middleware/test/utests/build/ctest-results.xml
+          reporter: java-junit
+          
+      # Upload artifact (middleware/test/utests/build/ctest-results.xml)
+      - name: Upload test result file (middleware/test/utests)
+        uses: actions/upload-artifact@v4
+        with:
+          name: ctest-results-middleware-utests-${{ github.run_id }}
+          path: middleware/test/utests/build/ctest-results.xml
+      
+      # Show failure
+      - name: Show failure details (if any)
+        if: failure()
+        run: tail -n 50 middleware/test/utests/build/ctest-results.xml || true
